// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBuH6YfNNWrKj0ojoiCSFpyVscKnZbnNiY',
    appId: '1:198504839481:web:07c726ba4d8bd4599550e8',
    messagingSenderId: '198504839481',
    projectId: 'green-home-pushnotification',
    authDomain: 'green-home-pushnotification.firebaseapp.com',
    storageBucket: 'green-home-pushnotification.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBf0nhUwHNlACov-mRC_LAc6tpNHt88uLQ',
    appId: '1:198504839481:android:f97b523979d140a69550e8',
    messagingSenderId: '198504839481',
    projectId: 'green-home-pushnotification',
    storageBucket: 'green-home-pushnotification.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC7vaPv-yfUlH4ZFx1J7Dwx3eS4zxYkkiI',
    appId: '1:198504839481:ios:166dcfe6ffe4151c9550e8',
    messagingSenderId: '198504839481',
    projectId: 'green-home-pushnotification',
    storageBucket: 'green-home-pushnotification.appspot.com',
    iosBundleId: 'com.example.greenhomeWebview',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC7vaPv-yfUlH4ZFx1J7Dwx3eS4zxYkkiI',
    appId: '1:198504839481:ios:166dcfe6ffe4151c9550e8',
    messagingSenderId: '198504839481',
    projectId: 'green-home-pushnotification',
    storageBucket: 'green-home-pushnotification.appspot.com',
    iosBundleId: 'com.example.greenhomeWebview',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBuH6YfNNWrKj0ojoiCSFpyVscKnZbnNiY',
    appId: '1:198504839481:web:8330caad0151db4d9550e8',
    messagingSenderId: '198504839481',
    projectId: 'green-home-pushnotification',
    authDomain: 'green-home-pushnotification.firebaseapp.com',
    storageBucket: 'green-home-pushnotification.appspot.com',
  );
}
